git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    commit = "0821747bb104161000150b5eb2ddc4c25317e36a"
)

local_repository(
    name = "Goodbye",
    path = "../Goodbye",
)
